# Generated by Django 3.2.6 on 2021-08-25 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_bn', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_bn', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanas', to='geo_spatial.district')),
            ],
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_bn', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('thana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unions', to='geo_spatial.thana')),
            ],
        ),
    ]
