# Generated by Django 3.2.5 on 2021-08-30 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_spatial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_bn', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255, null=True)),
                ('contact_no', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('remarks', models.TextField(max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thana',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thana',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='thanas', to='geo_spatial.district'),
        ),
        migrations.AlterField(
            model_name='union',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='union',
            name='thana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='unions', to='geo_spatial.thana'),
        ),
    ]
