# Generated by Django 3.2.5 on 2021-08-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_spatial', '0002_auto_20210830_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True),
        ),
    ]
