# Generated by Django 3.2.5 on 2021-08-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_spatial', '0003_alter_district_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='union',
            name='status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True),
        ),
    ]
