# Generated by Django 3.2.5 on 2021-09-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_spatial', '0005_auto_20210831_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeunit',
            name='contact_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policeunit',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policeunit',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policeunit',
            name='remarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
