# Generated by Django 3.2.5 on 2021-08-30 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_spatial', '0002_auto_20210830_1737'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warrant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrant',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='warrant',
            name='case_file_station',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='warrants_station', to='geo_spatial.thana'),
        ),
        migrations.AddField(
            model_name='warrant',
            name='case_type_section',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='warrant',
            name='concerned_police_unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='warrants', to='geo_spatial.policeunit'),
        ),
        migrations.AddField(
            model_name='warrant',
            name='court_given_other_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='warrant',
            name='court_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warrant',
            name='court_process_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='warrant',
            name='created_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='warrant',
            name='date_of_presentation_in_court',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='warrant',
            name='entry_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warrant',
            name='gr_cr_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='warrant',
            name='gr_cr_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='warrant',
            name='union',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='warrants', to='geo_spatial.union'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warrant',
            name='warrant_person_father_name',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warrant',
            name='warrant_person_name_age',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warrant',
            name='warrant_type',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warrant',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='warrants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warrant',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='warrants', to='geo_spatial.district'),
        ),
        migrations.AlterField(
            model_name='warrant',
            name='thana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='warrants', to='geo_spatial.thana'),
        ),
        migrations.AlterField(
            model_name='warrantfile',
            name='created_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
