# Generated by Django 3.2.5 on 2021-08-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0002_auto_20210830_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrant',
            name='tamil_officer_bp_no',
            field=models.TextField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='warrant',
            name='tamil_officer_info',
            field=models.TextField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='warrant',
            name='tamil_settlement_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='warrant',
            name='warrant_settlement_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='warrant',
            name='warrant_settlement_type',
            field=models.TextField(choices=[(1, 'OTHERS'), (2, 'NIR SUBMISSION'), (3, 'TAMIL'), (4, 'RECALL')], null=True),
        ),
        migrations.AlterField(
            model_name='warrant',
            name='warrant_type',
            field=models.IntegerField(choices=[(1, 'GR'), (2, 'GR Punishment'), (3, 'CR'), (4, 'CR Punishment'), (5, 'Others')]),
        ),
    ]
