# Generated by Django 3.2.5 on 2021-08-31 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_spatial', '0005_auto_20210831_2041'),
        ('warrant', '0004_auto_20210831_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrant',
            name='concerned_police_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='warrants', to='geo_spatial.policeunit'),
        ),
    ]
