# Generated by Django 3.2.5 on 2021-08-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0005_alter_warrant_concerned_police_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrant',
            name='approve_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='warrant',
            name='gr_cr_year',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
