# Generated by Django 3.2.5 on 2021-08-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0006_auto_20210901_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrant',
            name='approve_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Approved')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='warrant',
            name='gr_cr_year',
            field=models.PositiveSmallIntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='warrant',
            name='warrant_settlement_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'OTHERS'), (2, 'NIR SUBMISSION'), (3, 'TAMIL'), (4, 'RECALL')], null=True),
        ),
    ]
