# Generated by Django 3.2.5 on 2021-09-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0007_auto_20210901_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='warrant',
            name='approve_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Approved')], default=1),
        ),
        migrations.AlterField(
            model_name='warrant',
            name='gr_cr_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
