# Generated by Django 3.2.5 on 2021-09-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrant', '0008_auto_20210901_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
        migrations.AddField(
            model_name='warrant',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to='warrant/picture/'),
        ),
    ]
