# Generated by Django 3.2.5 on 2021-09-02 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warrant', '0009_auto_20210901_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrant',
            name='entry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='warrantfile',
            name='attachment',
            field=models.FileField(upload_to='warrant/files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='warrantfile',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warrant_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
